### ISSUE TITLE
Use original packages in composer

### ISSUE THREAD

**Issue by phaidon** [zikula/core#1832]
For some composer packages we are using own bundles. E.g. zikula/jquery-bundle

But I think there is no reason for that. The path (src/web) works without the original bundles and the bundles don't do anything additional (they are empty packages with a dependency to original packages).

So I suggest to use just the original packages. Or do I miss something?

@drak @craigh @cmfcmf 

Here the affected packages: zikula/jquery, zikula/jquery-ui, zikula/jquery-minicolors-bundle, zikula/bootstrap-bundle, zikula/fontawesome-bundle

**Comment by craigh** [comment]
After doing about an hour of research, it appears that all the proposals at composer were eventually denied and composer remains a php-only solution. Additionally, it also appears that bower is [losing its dominance](https://gofore.com/stop-using-bower/) in the js world and npm is gaining momentum.

**Comment by craigh** [comment]
but this is maybe the descendant of those discussions in composer: https://github.com/francoispluchino/composer-asset-plugin

**Comment by cmfcmf** [comment]
Maybe we should reconsider using NPM / Bower.

**Comment by Guite** [comment]
Probably related and interesting here: http://www.slideshare.net/nachomartin/webpacksf

**Comment by Guite** [comment]
Added blocker tag because I also think that our custom bundle packages are too cumbersome.

**Comment by Guite** [comment]
> javiereguiluz [9:27 AM]
> for Symfony apps I recommend you “webpack" and “yarn"

See also: https://www.youtube.com/watch?v=iINLewCGnuY

**Comment by craigh** [comment]
so - the reason we do this is because the original vendors are not symfony bundles. This means that there is no automatic management of web assets (images, css and js files).

Symfony will automatically copy **bundle** contents of `MyFooBundle/Resources/*` to `/web/bundles/myfoo/*` then these assets can be easily accessed in a template with `{{ asset('bundles/myfoo/images/image.jpg') }}`. This is important because ideally, we would like to make only the `/web` directory publicly viewable - assets that remain in `/vendors` or `/modules` are by default *not* visible to a browser - causing the site to break.

"faking" a bundle - e.g. zikula/jquery-bundle allows us therefore to silently manage this asset like any other. There is currently no ideal solution to this problem (although web pack and yarn look promising). The composer-asset-plugin above [lays out the case pretty well here](https://github.com/fxpio/composer-asset-plugin#why-this-plugin). But there solution is simply a generalized composer script similar to [one we have in use](https://github.com/zikula/core/blob/1.5/src/lib/Zikula/Composer/ManuallyInstallAssets.php) already.

This solution fails when using symfony's `assets:install` command (even ours fails in this regard).

So - as it stands I do not see a solution to this problem soon.
