### ISSUE TITLE
Performance problems with group memberships

### ISSUE THREAD

**Issue by shefik** [zikula/core#2013]
Group membership assignments can become a performance problem. I tested this on a dev site that has 59,500 users.

A 503 error is thrown when you attempt to view "Group Membership" here:
/groups/admin/membership/1

~~Also, the error is thrown when you attempt to register a new user. During the registration process, while attempting to add the newly created user to the default group, the Groups "get" function is called. Why are all the users being looped in "get", when you are just handling one user?~~ fixed!

Moreover, this functionality needs to be refactored, because it is unusable as-is on a large site.

**Comment by craigh** [comment]
> Group membership assignments can become a performance problem. I tested this on a dev site that has 59,500 users.

> A 503 error is thrown when you attempt to view "Group Membership" here:
/groups/admin/membership/1

at zikula.org we have ~4200 users. the `/groups/admin/membership/1` group page displays fine.

I suspect the problem is the user selector (the scrolling list). maybe we could employ an ajax lookup function there instead.

@shefik - haven't heard from you on this in a while, what do you think?

**Comment by shefik** [comment]
@craigh AJAX lookup can be useful.

**Comment by Guite** [comment]
Fixed in #3309
