### ISSUE TITLE
Session cookie name is not working

### ISSUE THREAD

**Issue by rallek** [zikula/core#2150]
securitycenter/session settings/Session cookie name:

If I change the session cookie name to e.g. _rksid the cookie will be still named _zsid

**Comment by craigh** [comment]
In order to fix this we need to do one of three things:

1. remove the ability to set the cookie name in the SecurityCenter completely and direct users to change the value in the config.yml file - but we probably don't want folks mucking around in that file.

2. remove the ability to set the cookie name as above but use a parameter to define the name (in `parameters.yml`) and direct users to change the value there instead.

3. use a parameter as in (2) but make the controller in SecurityCenter write the value to parameters.

I suppose there is a fourth option:

4. use the DynamicConfigDumper to save the config value there.

@cmfcmf @Guite thoughts?

**Comment by Guite** [comment]
1 and 2 are not desired imho as they would be a bc break.
3 and 4 sound more comfortable to me.

**Comment by cmfcmf** [comment]
:+1: for 3 or 4.

**Comment by craigh** [comment]
#4 is much harder than I thought because the config is like
```yaml
framework:
    session:
        name: _zsid
```

so the DymanicConfigDumper can't handle it (more than two levels). Apparently DynamicConfigDumper is more of a DynamicParameterDumper :wink:

**Comment by cmfcmf** [comment]
Can't you do 
```yaml
framework:
    session:
        name: %cookiename%
```
and then dump the `cookiename` parameter?

**Comment by craigh** [comment]
sure, that is option 3 :smile:
