### ISSUE TITLE
Attempted burglary recognised(seen) by PHPIDS

### ISSUE THREAD

**Issue by Alexalter** [zikula/core#2230]
With activation in security headquarters / configuration PHPIDS use I get with everybody new open side e-mail

Mail:
Der folgende Angriff wurde von PHPIDS entdeckt IP: 8x.xxx.xxx.xxx Benutzer ID: 2 Datum: 06. Feb 2015 Request Impact: 37 Betroffene Tags: xss csrf id rfe sqli lfi Betroffene Parameter: COOKIE.zikulaMobileTheme=%5B%22%5C%222%5C%22%22%2C%22a0c9aeb885b19b1c0df186eb545a5835bfd91130%22%5D, COOKIE._pk_ref_1_0cf4=%5B%22%22%2C%22%22%2C1423180757%2C%22http%3A%2F%2Fwww.al-werner.de%2Fnews%2F6%2F%22%5D, Request URI: %2Findex.php%3Fmodule%3Dsicherheitscenter%26type%3Dadmin%26func%3Dupdateconfig

Zikula 1.3.9

if somebody has a solution?

Nice greetings Alex

**Comment by Guite** [comment]
@Alexalter it would be interesting to know whether the problem occurs only with the dedicated mobile theme. Since the 1.4.x series the mobile theme is gone, because normal themes are based on bootstrap now and therefore display fine on mobile devices, too. But I bet the problem also happens with other themes... there not many users activating PHPIDS I think, so we do not have much feedback about it's behaviour in production yet.

**Comment by Guite** [comment]
@Alexalter did you ever experience any problems with other themes or did this occur only for the mobile theme?

**Comment by craigh** [comment]
closing for lack of response
