### ISSUE TITLE
Make sure we use beberlei/DoctrineExtensions v3

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2404]
https://github.com/beberlei/DoctrineExtensions/releases/tag/v0.3.0

> If you're still using Paginator, LargeCollections, Phing, PHPUnit or Versionable behaviours available in 0.1–0.3, you're welcome to use 0.3 – but do note, this functionality is now available in Doctrine core, no longer supported in this library, and was removed in 1.0.

The core only ships these extensions for legacy reasons (as documented in the upgrade-doc). This should fix https://github.com/zikula/core/issues/2329 @rallek.

- [ ] update composer to install v0.3 instead of dev-master
- [x] test with module using the old paginator.

**Comment by craigh** [comment]
good catch. I'm not sure about existing modules using old paginator though...

**Comment by rallek** [comment]
oh, if this avoids this BC I would be happy :-)

**Comment by cmfcmf** [comment]
I'm testing this with @rallek `VerySimpleDownload` module and it appears to work. However, I get the following error when creating a new entity / download:
![unbenannt](https://cloud.githubusercontent.com/assets/2145092/7030991/d43cc84a-dd68-11e4-8d20-0cada881c23c.PNG)

**Comment by Guite** [comment]
The workflow related issue is probably caused by a different implementation of `getActionsForObject()` in `1.3.x` vs. `1.4` modules. See https://github.com/Guite/MostGenerator/blob/master/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/cartridges/zclassic/controller/util/WorkflowUtil.xtend#L204
If I remember correctly the basic difference is that a workflow is not only an array, but an entity in 1.4 which behaves a bit differently / requires a slightly different implementation.

**Comment by cmfcmf** [comment]
I have the same error with Zikula 1.3.9. Therefore this is a MOST problem.
