### ISSUE TITLE
Consider to add Shariff

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2405]
https://github.com/heiseonline/shariff
German article: http://www.heise.de/ct/artikel/Shariff-Social-Media-Buttons-mit-Datenschutz-2467514.html

It adds these social media buttons to pages (if wanted) without actually sending data to Facebook, Google, etc. It displays the like count by querying the provider's api and therefore requires a PHP backend.
![unbenannt](https://cloud.githubusercontent.com/assets/2145092/7073336/0a26f6fc-def3-11e4-81b1-e953f3d07a2b.PNG)

**Comment by Guite** [comment]
Isn't this a feature for the Socialise module instead of the core?
https://github.com/phaidon/Socialise

**Comment by cmfcmf** [comment]
You're right.

**Comment by shefik** [comment]
@cmfcmf I haven't read all the docs from that site yet. But, my assumption is that enterprise-level companies would want data to be sent to the social networks for proper aggregation of analytics. Also, does this script violate any terms of use with the social networks, since it potentially bypasses intended/expected usage?

**Comment by shefik** [comment]
Side note: This requires PHP 5.4+.

https://github.com/heiseonline/shariff-backend-php
