### ISSUE TITLE
Categories questions

### ISSUE THREAD

**Issue by craigh** [zikula/core#2435]
Entities have a ManyToOne/OneToMany relation with Categories

In addition, an entity can currently have multiple relations in multiple registries.

these registries can have (but  typically do not have) the SAME parentId.
This necessitates the registryId column in the bridge table to discriminate this possibility
which I am wondering if this option is (1) wise and (2) practical
it is an edge case at best IMO
but it causes **many** headaches from a programming perspective as it deviates from a standard "Many to Many" relation.

real life example (from 1.3.x & current 1.4.0):
A Page entity can have two registries with the same parentCategory (e.g. Colors)
then when created, it should allow multiple choices within each

so created, we have:
Page1 -> reg1 -> array(Blue, Red, Yellow)
Page1 -> reg2 -> array(Blue, gold, pink)

so that would equal six rows in the bridge table

| pageid | regId | color(id) |
| --- | --- | --- |
| 1 | 1 | blue |
| 1 | 1 | red |
| 1 | 1 | yellow |
| 1 | 2 | blue |
| 1 | 2 | gold |
| 1 | 2 | pink |

you can see (1, 1, blue) and (1, 2, blue) only differ by the regId

but again I wonder aloud...
why would anyone want something like this?
it seems impractical

@cmfcmf @Guite @shefik @matheo

**Comment by Guite** [comment]
Functionally category registries are useful indeed, because they allow modules coupling to a registry instead of a concrete categories subtree.
A site admin can even change these assignments on a site without coding or create additional ones.
You could have three (equal or different) category fields in module XY, pointing to different sub trees. For example you could use a media module with 1. a topic category 2. some sort of organisational classification and 3. another category.

**Comment by craigh** [comment]
sure, but that is not what I am talking about. All that is still possible if the registryId column is removed from the bridge table. the only thing that is not possible AFAICS is the ability to double-assign the same subtree.

**Comment by Guite** [comment]
> All that is still possible if the registryId column is removed from the bridge table.

If the registryId column would be removed, then you can not update/remove existing mappings if the admin changes a registry to another subtree in the categories administration later on.
