### ISSUE TITLE
Call to a member function incrementCounter

### ISSUE THREAD

**Issue by AlexL777** [zikula/core#2453]
Hello Developers,

I've got a problem and although I use Zikula 1.4 RC under PHP 5.5 and have at the Static Pages this error message. The error is displayed when I click on the Zikula Home on the link "Static Pages".

     Fatal error: Call to a member function incrementCounter() on null in /www/htdocs/xxxxxxx/modules/Pages/lib/Pages/Access/Page.php on line 165
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Error: Call to a member function incrementCounter() on null

Can I perhaps someone help? Thank you in advance.

**Comment by craigh** [comment]
Thanks for reporting the error, but this is a Pages module error.

The Pages module is currently under heavy development (if you are using the master branch version). It requires a non-integrated Core patch in order to work.

If you require something to work immediately, please use released versions of the software (Core 1.3.9 and Pages 2.6.0).
