### ISSUE TITLE
Hooks Page Needs to be Converted to Routes

### ISSUE THREAD

**Issue by shefik** [zikula/core#2466]
The Hooks page needs to be converted to routes

`/index.php?module=example&type=admin&func=hooks`

**Comment by craigh** [comment]
I tested this a bit and see that the URL works properly with PostCalendar (a 'true' 1.3-type module) and Dizkus (a 'hybrid' 1.4-type module ~ has routes, but uses legacy controllers and smarty templates). It does **not** work at all with the new Pages module (which is an FC 2.0.0-type module). So I removed by BC-Break label.

**Comment by craigh** [comment]
ok - quick clarification. I know this ticket is about a simple conversion to routes, but the Hooks UI is not easily converted because it "pretends" to be a service of the providing module and so the URL/route looks like it belongs to the provider/subscriber, but in reality it is served from the Extensions module, so it is more complicated than it seems.

additionally, it is not currently compatible with fully 2.0.0 modules (see above).

**Comment by shefik** [comment]
Refs. https://github.com/zikula/core/issues/2448

**Comment by craigh** [comment]
the solution to this issue is quite complex. #2448 may not solve it. If you have ideas, please share.

**Comment by craigh** [comment]
closed by #2478
