### ISSUE TITLE
boostrap theme not all files are used

### ISSUE THREAD

**Issue by rallek** [zikula/core#2474]
I am looking at the boostrap theme to learn for an own one. If I am right, the templates in /view/body are not used except of 1col.tpl. All others are not looking like bootstrap. So all the variables in themevariables.ini are also not used.

Bootstrap theme itself is working (as long as I can see)

**Comment by craigh** [comment]
IMO the entire bootstrap theme should be removed. it is a relic of development which has been superceeded. @Guite?

**Comment by Guite** [comment]
I do not know. ping @phaidon ?

**Comment by rallek** [comment]
If we remove it I would be happy to see another bootstrap example ;-)

But you are right. The current one looks not perfect. Unfortunally I am at the beginning of learning so I can not make one which is better.

**Comment by Kaik** [comment]
This theme is the best theme to start making new one is dead simple and very light (there is nothing in it) and I think it's needed. I use it as my theme template. @rallek there is not much to do with this theme so it will be fully featured bootstrap theme.

**Comment by phaidon** [comment]
I agree Kaik.

**Comment by craigh** [comment]
Ok, removing is out but still the OP hasn't been addressed

**Comment by Kaik** [comment]
Well I just have quick look and to make it fully bootstrap two files need to be to converted (not including modules folder )are https://github.com/zikula/core/blob/1.4/src/themes/Zikula/Theme/BootstrapTheme/Resources/views/body/2col.tpl and https://github.com/zikula/core/blob/1.4/src/themes/Zikula/Theme/BootstrapTheme/Resources/views/body/2col_w_centerblock.tpl this is very easy change class to col-lg-3 and col-lg-9 or something instead of grid_3 grid_13
Additionally we could leave head and body tag in header.tpl while moving rest(menu) to additional file. So two things are not messed together head and menu.
https://github.com/zikula/core/blob/1.4/src/themes/Zikula/Theme/BootstrapTheme/Resources/views/includes/header.tpl

I do not know what else expect from it as it's power is in simplicity.

**Comment by Kaik** [comment]
@rallek I do not fully understand what you mean saying 

>If I am right, the templates in /view/body are not used except of 1col.tpl

The idea is that end user can change it to for example 2col.tpl etc. some of those files might be not used by end user at all, there are just options which end user have to chose from.

**Comment by rallek** [comment]
long time ago. But as I am now starting a simple site based on the bootstrap theme I will see it again in short time.

**Comment by craigh** [comment]
closed by #2553
