### ISSUE TITLE
Build 623 - No directory install

### ISSUE THREAD

**Issue by Portugao** [zikula/core#2496]
Like in the documentation said, i get a redirect to the installer, if i want to install and i get the following error:
```
The requested URL /install was not found on this server.
```
Did I misunderstand something?

**Comment by craigh** [comment]
do you have an `/install` directory? (you shouldn't)

**Comment by jguille2** [comment]
Hi,
- There is not an install directory, but '/install' redirect is the way of the web installer.
- I had this problems before, and the origin was the 'AllowOverride directive'. I've tested, and I can install build 623.

@portugao Check your apache config, and set AllowOverride to All

**Comment by Portugao** [comment]
No, I don't have.

**Comment by Portugao** [comment]
I'm customer of a hosting company. I wonder if they can do for me....

**Comment by Guite** [comment]
@Portugao you can ask them if there is anything preventing a `.htaccess` file from being processed - especially rewrite rules for short urls.

**Comment by Portugao** [comment]
Solved. The htaccess file was missing. Seems to get lost during upload of zip file......

**Comment by jguille2** [comment]
If Michael confirms the problem is in the Apache directive, I think we can close this issue, because this is  a documented [requirement](https://github.com/zikula/core/blob/1.4/INSTALL-1.4.0.md) "Zikula requires AllowOverride All and the mod_rewrite module (be aware the Apache 2.3.9+ has changed the default setting for AllowOverride to None)."

**Comment by jguille2** [comment]
Ups!
 I wrote the last comment before reading closing comment. ;)
