### ISSUE TITLE
datautil email obfuscation.

### ISSUE THREAD

**Issue by robbrandt** [zikula/core#2501]
Can I ask this to be changed?  The "email obfuscation" in https://github.com/zikula/core/blob/1.4/src/lib/util/DataUtil.php from line 201-209.
Just a gripe I guess.  Real data shouldn't be obfuscated, because it limits the ability to find what you're looking for in a database query.  If you want to obfuscate at display time, fine, do it there.  Plus I have run into problems where it doesn't get *un* obfuscated properly and it gets re-obfuscated badly.  Ending up will long strings of what users regard as "garbage".
Gripe over :)

**Comment by craigh** [comment]
using version?

**Comment by robbrandt** [comment]
Using version 1.3.x currently, but the obfuscation is still there in 1.4 master branch.

**Comment by cmfcmf** [comment]
I am 100% sure this has been removed by @drak at some point ("it does not help anyways and is dumb" or similar he said). But now I'm puzzled because it's still in 1.4 and 1.3 :boat:

**Comment by robbrandt** [comment]
I agree with Drak.

**Comment by Guite** [comment]
@robbrandt as this protection against bots collecting email addresses is part of `formatForDisplay` the encoded version should not occur in a database normally.

If this happens for you using a MOST module the reason is probably that you store data in another function than `edit` which is excluded in the `formatTextualField` method of your entity base class (called by the post load callback).

Example: https://github.com/zikula/core/blob/1.4/src/system/ZikulaRoutesModule/Entity/Base/AbstractRouteEntity.php#L898

Refs https://github.com/Guite/MostGenerator/issues/624



If this functionality is removed in 1.4 this would be a BC break.
Maybe it would be possible to have a setting / modvar for adjusting the behaviour? Then people could switch it off if desired.

**Comment by craigh** [comment]
> I am 100% sure this has been removed by @drak at some point

@cmfcmf I think you are thinking about the obfuscation in the `config.php` file (which is now stored in custom_parameters.yml`).

I think @robbrandt is talking about user passwords or emails?

**Comment by robbrandt** [comment]
@craigh I am talking about emails.
@Guite I will look into that, it's in SurveyManager.

**Comment by craigh** [comment]
@robbrandt @Guite status on this? I think it should be closed as notcore.

**Comment by Guite** [comment]
Fine for me. The whole formatForDisplay thingy will be replaced by Twig anyway. I can live with what we have now for the meantime ;-)

**Comment by robbrandt** [comment]
I haven't had a chance to see why formatForDisplay seems to be used in an update procedure, but it's on my list of things to do when I get back to working on this module.  If it's a genuine issue it may call for a patch to the 1.3 branch, and I can ask for this issue to be reopened.
