### ISSUE TITLE
Centralize all the documentation and decide for a system

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2503]
We need to centralize all the Zikula documentation and decide for a common language / markup to convert it to.
### Places where documentation is currently:
- https://github.com/zikula/core/wiki
- https://github.com/zikula/core
- https://github.com/zikula/core/tree/master/src/docs
- https://github.com/zikula/zikula-docs
### Possible markups / systems to use

| Place | Markup | + | - |
| --- | --- | --- | --- |
| GitHub Wiki | Markdown, AsciiDoc, ReStructuredText | no need for extra servers / scripts | not that flexible, everyone can edit without further notice |
| Separate repository (zikula/zikula-docs) | reStructuredText | very flexible, used by Symfony, embeddable into zikula.org, not too easy to write | need for an extra server / script / module to compile and display it |

Feel free to add to the list of possibilities.

**Comment by craigh** [comment]
:+1:

**Comment by craigh** [comment]
also - need to figure out a way to post it to zikula.org

**Comment by craigh** [comment]
The docs must be version-able somehow. Investigate how symfony does this. 

much of our documentation will be pointing to third party docs, e.g. Doctrine, Symfony, etc

**Comment by craigh** [comment]
http://stackoverflow.com/tour/documentation

**Comment by cmfcmf** [comment]
> http://stackoverflow.com/tour/documentation

The issue is that the `zikula` tag at StackOverflow isn't active enough to allow documentation.

**Comment by craigh** [comment]
agreed. That could change though if we desired it I think.

**Comment by Guite** [comment]
@cmfcmf why is an extra repository embeddable into zikula.org, but the GitHub wiki not? A GitHub wiki is also a git repository. You can for example do `git clone git@github.com:zikula/core.wiki.git`.

**Comment by cmfcmf** [comment]
> @cmfcmf why is an extra repository embeddable into zikula.org, but the GitHub wiki not? A GitHub wiki is also a git repository. You can for example do git clone git@github.com:zikula/core.wiki.git.

sure.

**Comment by Guite** [comment]
Last week I talked with @rallek about **user docs** and we agreed that it would be advantageous to have these directly inside the application instead of separate documents.

How about this (again, for user docs):

Step 1:
- establish a structure for module-based documentation in Markdown format (this should consider the possibility to add translations)
- automatically provide a *help* or *manual* link in the admin menu of a module (similar to the *hooks* link) if Markdown files are available (could be exposed using a capability to avoid file system scans); use markdown parser to display the docs in html
- default way to *show* this documentation, for example using a modal window or a sidebar (like mmenu, but on the right side)

Step 2:
- maybe implement an additional functionality to create a *complete manual* by combining the markdown files of all available modules into one document (whereby each extension and theme are included as a sub chapter)
- possibility to create pdf files for single extensions or the complete manual

Benefits:
- documentation is maintained directly with the component instead of elsewhere
- context sensitive: users find documentation right at the page where they need it
- easy to handle for different versions (documentation is updated together with the code)
- easy to avoid that docs become outdated
- easy way to contribute as Markdown is simple
- easy to translate
- possibility to create a central documentation automatically (using CI) to publish it on zikula.org for example

Aspects to think about:
- updating translations: maybe we can/should use gettext or something else so that updates can be reflected into existing translations without having to review everything again and again
- deep links between the docs of different extensions (e.g. link a doc section of *AdminModule* inside the docs of *FormiculaModule*)

**Comment by craigh** [comment]
sounds like https://github.com/craigh/DocTastic which I started and abandoned years ago.

**Comment by Guite** [comment]
Docs from core repo are now automatically deployed to https://docs.ziku.la/ using Couscous and hosted by GitHub Pages.
Docs from the wiki have been merged already, wiki is closed.
Docs from zikula-docs will be merged into that (and converted from rst to markdown) now.
Also things will be restructured.
So decision is made, hence I'll close this issue.
