### ISSUE TITLE
[Core 2.0][Discussion] Page Vars vs. Page Assets

### ISSUE THREAD

**Issue by craigh** [zikula/core#2559]
Currently in Core 1.x we have a [PageUtil](https://github.com/zikula/core/blob/1.4/src/lib/util/PageUtil.php) that manages items to be added to a page before rendering. These currently include *values* like a page *title* or *metatags* and *assets* like *stylesheets* and *scripts*. In the 1.x api items like the title are referred to as `single valued`, others are `multi valued`. Additionally, these items must be [*registered*](https://github.com/zikula/core/blob/1.4/src/lib/legacy/Zikula/Core.php#L572-L582) before they are utilized. (note 'title' is the **only** registered single value item).

In Core 2.0 I am wondering if we should separate these items into `vars` and `assets`. The main difference between the two is that `assets` must be located (and possibly overridden) and then rendered into the page through a filter mechanism complete with proper tags, etc, whereas the `vars` are not traditionally added through a filter but as simple values that the theme designer manually renders (e.g. `<title>{pagegetvar name='title'}</title>`).

please note: *images*, although a page asset, are not managed through this functionality.

so questions:
1) Should we separate these items?
2) Should we require pre-registration of utilized values?
3) What don't I know about this? I'm sure I'm forgetting something...

refs #2489

**Comment by Guite** [comment]
My opion about this:

1) Yes. Let's treat assets using Symfony assets functionality while utilising another mechanism for the remaining vars.
2) Probably a pre-registration is not required. Of course we need some kind of convention for common vars (like the title). There is also no pre-registration for modvars, though. But of course a theme designer can not assume all circumstances of the context (active extensions, running modules, and so on). Hence in case a var does not exist, an empty value or null should be returned (instead of raising an exception or something).
3) I think you got the most important aspects already. Remember all the legacy way of how things work is based on historical evolvements.

One additional thought about assets:
4) JavaScript files should either be included in the `head` section or (in most cases nowaydays) at the end (right before `/body`) for improved site performance. So I suggest that all JS files are included at the end by default in future unless `head` is explicitely desired for a certain file.

**Comment by cmfcmf** [comment]
I agree with @Guite except for 4), js should be included in the head by default for BC.

**Comment by Guite** [comment]
In 2.0.0 we should prefer the footer though, like discussed in Slack.

**Comment by cmfcmf** [comment]
> In 2.0.0 we should prefer the footer though, like discussed in Slack.

Yes, edited my comment.
