### ISSUE TITLE
some css is missing

### ISSUE THREAD

**Issue by rallek** [zikula/core#2570]
In ci build 18 in a fresh install of 1.4.1dev some css is missing. Axel says it might be related to the less generator

The admin thme is broken. All menu items are as a normal list.

**Comment by shefik** [comment]
In Zikua 1.4.1 build 35, the browser throws an error, about this file missing:

`/web/bootstrap-font-awesome.css`

**Comment by craigh** [comment]
I guess Jenkins is not building and including that file like composer does. @cmfcmf and @phaidon please work together to make Jenkins do the job.

**Comment by craigh** [comment]
I deleted the idea I had above ^^^ because I looked at the history of the file and other commands within it, and it appears that the `--no-scripts` option must remain.

I looked at creating a console command to run the bootstrap compiler and couldn't figure it out because of the multiple options of run directories (running from CLI, composer, jenkins). I guess I need someone smarter than me @cmfcmf

**Comment by cmfcmf** [comment]
Fixed as of build 49.

**Comment by craigh** [comment]
thank you @cmfcmf !

**Comment by rallek** [comment]
Great!

**Comment by rallek** [comment]
Have a look at my fresh install of ci build 68: http://koester123.de/ That looks not complete...
I think we have to reopen the ticket

**Comment by craigh** [comment]
there is a typo. I already found. just a moment.

**Comment by craigh** [comment]
this is neither a typo nor the same issue. It is a logic issue that doesn't seem to affect me the same as you.

**Comment by craigh** [comment]
I hope this commit solves it. test and let me know

**Comment by rallek** [comment]
Build 70 from ci server is working well. Thanks for that!
