### ISSUE TITLE
Fix pageVars TODO?

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2571]
https://github.com/zikula/core/blame/master/src/lib/Zikula/Bundle/CoreBundle/Twig/Extension/CoreExtension.php#L290

I am unclear why this TODO is there. @craigh

**Comment by craigh** [comment]
I don't think we need to open tickets for every @todo in the code :smile: 

There are many @todo in the Core-2.0 ThemeEngine and related classes because the code is not finished. My goal was to get the code to "work" and then to refactor it to improve efficiency and testability, etc.

This particular @todo is there because the method name is called `pageAddVar()` (implying _adding_ a var), but the service method being used in that case is a `set` method which doesn't *add* but *sets* (because the service doesn't have an *add* method I think). It also relates to questions in #2559 and the general management of pageVars in general.

**Comment by cmfcmf** [comment]
> I don't think we need to open tickets for every @todo in the code :smile:

In general, yes. But this particular line is wrong. It should either `add` it (like said in the TODO) or `set` it as an array with only one value. The way it currently is results in errors.

**Comment by craigh** [comment]
errors? I've seen none so far. Do you have an example?

**Comment by cmfcmf** [comment]
> errors? I've seen none so far. Do you have an example?

`{{ pageAddVar('header', 'stuff') }}`

**Comment by craigh** [comment]
Is this already in use somewhere or are you trying it out? But to be fair, this is exactly why there is a @todo in the code. this *add* functionality hasn't been implemented - therefore it is @todo

**Comment by cmfcmf** [comment]
> Is this already in use somewhere or are you trying it out?

Just trying around.

**Comment by craigh** [comment]
> Just trying around.
:+1: 

breaking things now is good :smile: 

but I still don't think this ticket is worthwhile. :boat:

**Comment by cmfcmf** [comment]
Thanks!
>
>
