### ISSUE TITLE
Add bc to $view->addPluginDir

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2578]
ZK 1.4. MOST modules use 
```php
$view->addPluginDir('system/Zikula/Module/AdminModule/Resources/views/plugins');
```
which now needs to be 
```php
$view->addPluginDir('system/AdminModule/Resources/views/plugins');
```
A simple `if` should be added to the function to check for this change.

**Comment by craigh** [comment]
I'm not following how this is a core problem or how it could be fixed by the core?

**Comment by craigh** [comment]
I also don't understand why a MOST module would need to include plugin directories from a  core module in the first place? @Guite

**Comment by Guite** [comment]
Probably for legacy reasons.

**Comment by Guite** [comment]
https://github.com/Guite/MostGenerator/commit/731ec6184f8ed2339847616710643a9ba10e2be3

**Comment by craigh** [comment]
I think this is a NOT CORE issue. this is a problem with the generator using a non-api-compliant method of access the View object (at least IMO).Since the generator has been updated, I think it should be closed. I also think that the generator should consider dropping this type of access to the View object...

**Comment by Guite** [comment]
At the moment it is not reasonable to drop that, because the core loads the `Admin` module plugins (like adminheader and adminfooter) only if `type=admin`, but not for `type=foo&lct=admin`. We can drop it for 2.0 though because we have the new annotation now so the core knows when to load those plugins independent from the url.
https://github.com/Guite/MostGenerator/commit/7abd24ee853e3124f430cbf646130b811254f312

**Comment by craigh** [comment]
Seems like it would have been better to integrate that fix into the core. Probably [about here](https://github.com/zikula/core/blob/1.4/src/lib/legacy/Zikula/View.php#L243) you could do something like `FormUtil::getPassedValue('lct')` and solve it.

**Comment by craigh** [comment]
I still think we should close this ticket.
