### ISSUE TITLE
Consider Puli

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#2631]
- [ ] Wait for Puli 1.0.0 to be released (should be end of 2015, beginning of 2016)
- [ ] See if it can be integrated in the core.

**Comment by Guite** [comment]
https://www.youtube.com/watch?v=nRqwGGROvfw

**Comment by Guite** [comment]
https://github.com/puli/symfony-bundle

**Comment by craigh** [comment]
having watched 25 minutes of the video, I do not think Puli is something we need to be looking at right now. We are tightly coupled to Symfony - by design - Puli would loosen that coupling and at this point in our development, I don't think this is worth investigating. When and if Symfony itself supports Puli, then we might look at it again. Since I doubt this will happen in Symfony 4 (I've not read about it), I''m moving this to *Future Ideas*

**Comment by Guite** [comment]
Closed in favour of Symfony 4 and Symfony Flex.
