### ISSUE TITLE
Disable hooks in Routes module

### ISSUE THREAD

**Issue by craigh** [zikula/core#2636]
It seems odd to me that hooks are enabled in any way for the routes module. I cannot see a use-case or need for hooks in routes, either as a provider or subscriber.

The current state enables Routes as a subscriber. This should be disabled, IMO.

opinions? @Guite @cmfcmf

**Comment by craigh** [comment]
@Guite does the generator provide for a way to disable hook provision/subscription at the model level? If not, it should do so. A simple checkbox - 'enable module as hook provider' and 'enable module as hook subscriber'. maybe even at the entity level? hooks are quite complicated and this may not be easily possible I guess.

**Comment by Guite** [comment]
There is no setting on the model level for that yet.

Regarding your customisation:

1. I like https://github.com/zikula/core/compare/184740fab8...b7cd74ecb6 much more than https://github.com/zikula/core/blob/routing-overhaul/src/system/RoutesModule/RoutesModuleVersion.php because it just removes the hook-related settings instead of everything.

2. Ensure adding the version class you implemented to `markFiles` in the model.

**Comment by craigh** [comment]
> I like 184740f...b7cd74e

as I said elsewhere, leaving a blank array for capabilities results in errors. I tried both ways (obviously) and was forced to go with the current solution.

**Comment by cmfcmf** [comment]
```
unset($meta['capabilities']['thesubscriberthing']);
if (count($meta['capabilities']) == 0) {
  unset($meta['capabilities']);
}
```
