### ISSUE TITLE
Refactor Extmenu block

### ISSUE THREAD

**Issue by craigh** [zikula/core#2676]
refs #2674 

 - refactor function.menutree.php plugin (leave for BC?)

**Comment by craigh** [comment]
refs #2031. we should probably fully replace Extmenu (and all menu blocks) with external libs.

**Comment by craigh** [comment]
there should only be *one* 'active' checkbox (not one per language)


![screen shot 2016-03-24 at 8 30 50 am](https://cloud.githubusercontent.com/assets/350048/14017051/ca05b35e-f19a-11e5-85fc-cc3f18dec95f.png)

**Comment by Guite** [comment]
No. As far as I remember there happened to exist a checkbox per language also in older versions. This is useful if you do not want menu items appear in (let's say) a secondary language, but only in the primary one. This is quite common because a site owner does not always want all pages translated, but just the most important ones.

**Comment by craigh** [comment]
ok! :+1:

**Comment by Guite** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;RwknNCNK&#x2F;2-menu-blocks-2031-2675-2676"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Menu blocks #2031 #2675 #2676</a>

**Comment by craigh** [comment]
Closing as This will NOT be done - ExtMenu will not be updated.
