### ISSUE TITLE
legacy modules always use home realm in theme

### ISSUE THREAD

**Issue by pheski** [zikula/core#2691]
I can use the dropdown options to change how Home and Admin look (1 column, 2 columns, 2 columns with centerblock, 3 columns, 3 columns with centerblock), but selecting these options makes no different when applied to Master.  This means, all my pages have the same layout as Home - in my case 3 columns with centerblock.

As I understand it, Master should control the display of all pages except Home and Admin.

**Comment by craigh** [comment]
try deleting the cache after changing it (the entire `app/cache/prod` folder)

**Comment by pheski** [comment]
Delete the app/cache/prod folder?
Empty the app/cache/prod folder?

There's a boatload (3.4 mb) of stuff in it...

P

**Comment by craigh** [comment]
delete the entire folder. it will rebuild it self.

**Comment by pheski** [comment]
Done. No joy.  I changed master to one column, saved, dumped prod - still shows three columns.

**Comment by craigh** [comment]
This is actually not the problem. Although it (obviously) appears that way.

the problem is that the theme engine is not properly determining the realm to use for legacy modules. (e.g. modules that use routes like `index.php?module=News...` It works properly for Core-2.0 spec modules. Instead they are all using the home realm template. so it appears to not be working as you would expect.

I've updated the title to reflect the problem.
