### ISSUE TITLE
Deprecated: Methods with the same name as their class will not be constructors

### ISSUE THREAD

**Issue by shefik** [zikula/core#2766]
Under 7.0.0, an attempt to install Zikula 1.4.2 build 103 throws this error immediately at /install:

```
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Smarty has a deprecated constructor in /vendor/drak/smarty/Smarty/Smarty.class.php on line 64
```

Under PHP 5.6.10, this issue does not exist, so the Smarty class name (or method) needs to be changed, in order for Zikula to work under PHP 7.0.0.

**Comment by craigh** [comment]
We will not be updating Smarty. It is a vendor.

Smarty is being removed from Core-2.0 so that version of Zikula will be compatible with PHP 7 but Core-1.4 will never be I suppose.

ping @cmfcmf

**Comment by shefik** [comment]
Ok, it's coming from drak's vendor code.

**Comment by craigh** [comment]
which is a copy of the original. If you are interested, you can submit a PR there. Drak is long gone, but I can merge it there if you submit it.

**Comment by ccandreva** [comment]
If you want to run under PHP 7 and have access to php.ini, you can update your error_reporting to add & ~E_DEPRECATED , so that PHP doesn't throw warnings for the use of depricated constructs.  I'm running php 7.0.15 on Fedora 25 with the following:
`error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT`
