### ISSUE TITLE
Reenable search block options

### ISSUE THREAD

**Issue by Guite** [zikula/core#2861]
During #2853 the search block's options from other modules have been disabled.
To make this work again probably some custom form handling is required.
Maybe this can be done with a transformer: http://symfony.com/doc/current/cookbook/form/data_transformers.html

See these todo markers:
- https://github.com/zikula/core/blob/1.4/src/system/SearchModule/Resources/views/Block/search_modify.html.twig#L4
- https://github.com/zikula/core/blob/1.4/src/system/SearchModule/Block/Form/Type/SearchBlockType.php#L53

**Comment by craigh** [comment]
EVENTUALLY - the search 'plugin' concept must be replaced by a DIC tag. That will probably solve this. But I'm not sure a BC method can be created in the middle. possibly.

maybe this must be done now for 1.4.3 since the module is now changed. Honestly, I've not really looked carefully at this issue yet.
