### ISSUE TITLE
adminMenu problem

### ISSUE THREAD

**Issue by craigh** [zikula/core#2894]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3

### Expected behavior
proper display of admin menu

### Actual behavior
no menu items
![screen shot 2016-06-14 at 11 49 35 am](https://cloud.githubusercontent.com/assets/350048/16049645/838114c4-3226-11e6-91e3-89e4ea05b1ca.png)

It seems to work properly in the panel view
![screen shot 2016-06-14 at 11 50 33 am](https://cloud.githubusercontent.com/assets/350048/16049659/8e682dc8-3226-11e6-8740-6feccc5e16b6.png)

**Comment by craigh** [comment]
@Kaik did this initial work on this I think?

**Comment by Kaik** [comment]
I will take a look on this today but this is wired as profile module is still smarty module and it does not use the new header for twig. It does work for smarty as I just installed it on 1.4.2 the only thing that has changed since then is users module so I bet it is because profile module loads users module links here 
https://github.com/zikula-modules/Profile/blob/master/Api/AdminApi.php#L366 
while this function does not exist anymore in your version of users module.

**Comment by Guite** [comment]
> the only thing that has changed since then is users module
No, I also continued the Admin module refactoring in 1.4.3, migrating more stuff to Twig and Symfony forms.
But of course it could also be related to the new Users module.

**Comment by Guite** [comment]
Ideally test 1.4.3-dev with another smarty-based module, like Content.

**Comment by Kaik** [comment]
It may work for the panel because panel uses a different function to collect links... I think... hmm... wait it should generate error for panel as well because this function does not exist anyway``` 'links' => ModUtil::apiFunc('ZikulaUsersModule', 'admin', 'getLinks'));```
@Guite I do not think your changes can affect this. 
@craigh is there anything under Users Module link in panel view ? there should be nothing there if I;m right...

**Comment by craigh** [comment]
IMO this has nothing to do with smarty. The links come from an API call and is php only.

> is there anything under Users Module link in panel view ?

yes - all is present as expected.

**Comment by Kaik** [comment]
>IMO this has nothing to do with smarty. The links come from an API call and is php only.

Well it does since if it is smarty plugin calling to display thise links, then it has nothing to do with changes I have made because they work only in twig whole AdminInterfaceController works for twig while smarty is using functions in AdminController.

>yes - all is present as expected.

Just to confirm have you checked it under top UsersModule link or inside Profile module ->Users Module because this makes difference.

**Comment by Kaik** [comment]
I'm still confused how come this can work in panel view since  ```ModUtil::apiFunc('ZikulaUsersModule', 'admin', 'getLinks'));``` does not exist in new UsersModule

**Comment by Kaik** [comment]
I cannot test it now as I'm away from my development center ;) I will be back on Sunday

**Comment by Guite** [comment]
Content has the same problem, so this is not specific to Users.

Added a first fix in f6888887d873af742f4aaa9dc412650b961c915f
The actual correction must probably be done in AdminInterfaceController#menuAction() where it calls `$linkCollection = $this->get('zikula.link_container_collector')->getLinks($adminModule['name'], 'admin');`

**Comment by Kaik** [comment]
@Guite legacy modules should not use AdminInterfaceController only stick with AdminController. This was the idea behind creating AdminInterfaceController - to left legacy untouched where it is, and new functionality for Twig place somewhere else, where it will not affect anything but Twig. Then inform devs of a new spec for twig. I do not understand what you want to correct there, as it is not even called for those modules.

Only thing that is similar in both profile and content in admin links is usage of  ```links =>``` submenu, but still it is still legacy now we have link container so it should work.
I need to install all those things and see what is happening.
