### ISSUE TITLE
Listener theme.init not being called by Twig templates

### ISSUE THREAD

**Issue by shefik** [zikula/core#2909]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.3
| PHP Version       | 5.6

### Expected behavior

The listener `theme.init` is expected to be called when using Twig templates.

### Actual behavior

The listener is currently only being called when using legacy Smarty templates.

**Comment by craigh** [comment]
what need do you have for this event?

**Comment by shefik** [comment]
Setting pagevars via the listener.

**Comment by shefik** [comment]
As a workaround, I'm now setting the page vars under `core.postinit`, which does get called when using Twig.

**Comment by craigh** [comment]
Please use a Symfony event. For example the response events

**Comment by shefik** [comment]
Ok.

**Comment by craigh** [comment]
I am closing this ticket because theme.init works as it has been expected to - e.g. only in smarty themes. 

The [docs](https://github.com/zikula/core/blob/1.4/src/docs/Core-1.x/events.rst) say:
> Occurs just before Zikula_View_Theme#__construct() finishes. The subject is the Zikula_View_Theme instance.

this of course is *impossible* with Twig-based themes as there will not be a `Zikula_View_Theme` instance 😉 

As stated above, use the symfony response event for modifying the response. This is done in several places in the core as well.
