### ISSUE TITLE
upgrade doctrine extensions 

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#3057]
https://github.com/Atlantic18/DoctrineExtensions/releases/tag/v2.4.22

**Comment by craigh** [comment]
will automatically upgrade https://github.com/zikula/core/blob/1.4/composer.json#L64

**Comment by Guite** [comment]
Done ;-)

**Comment by Guite** [comment]
I've added this for 1.4.4, see https://github.com/zikula/core/compare/8450dbda94ce0714988504e6945a3d008ca2ef53...a17492c8a39d047188536d5e3ee7e5547c08c80c

If this turns out as not correct (because there needs to be another 1.4.3 build), both issue and changelog entry need to be moved to the 1.4.3 milestone.
