### ISSUE TITLE
Spam protection question - issues and future implementation.

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3078]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4 - future releases.
| PHP Version       | 5.6

First of all, this was working fine for me since 2007. 
Now I need to change this question quite often either bots can solve it or they get help from a human. Second, there is no way to translate it which makes the site not fully multilingual.

I think that this should be removed from ZAuthModule. I think ZAuthModule is not a good place for it.
(I know I can disable it by not adding the question.)
We could create new system module (AntiSpam) where this kind of security could be served across a site using hooks. Not only registration form but other forms as needed. Spam protection question could be improved (multiple questions/translations) as well other spam protection solutions can be added like reCaptcha.
I do not think spam protection should be left to 3party modules as this is a common feature in most of CMS and basic spam protection should be implemented as a core feature.

This ticket is not about solving, a particular problem but more a discussion about the feature itself and it's future in core.

**Comment by robbrandt** [comment]
I'll weigh in since this is an issue for me as well.

I think your suggestion of a dedicated module is good, as long as it allows for 3rd party plugins.  There are SO MANY different spam solutions out there, and some might work well for some situations but not for others.  I don' think this is a one size fits all solution.

I have a solution that ends up working well for me, which I haven't polished enough to contribute.  For me, my biggest problem is forum spam.  And the forum spam originates largely from 3rd world countries.  I hacked the user module to do an IP address location lookup, and added a configuration field to contain country codes where a new user registration would be moderated.  So, for example, a new user from Pakistan would be able to register, but I have to approve the account.  Which I almost never do.

This solution depends on an IP address location service, which I hardcoded to be https://freegeoip.net/.  Free Geo IP is an open source project/service based on GO, so it can't be completely integrated into Zikula.  It would be better if there were a good php function for this, but I haven't looked too hard.

In any case, this solution has basically solved my spam problems.  I also use the older BadBehavior module, which needs to be updated to a new version of their library.  Because of this, I don't really know how much it helps me.  There's also Akismet, which I do not use.  So, there's good examples of current 3rd party modules and other approaches that may not work well as a genuine "core" solution.

**Comment by Kaik** [comment]
It will, of course, allow 3party modules/plugins. The reason, why I think it would be better for this to be a core module or even a system module, is that those are maintained with core and this functionality is important enuff to be part of the core. Spam protection question already is part of the core but it is implemented in a wrong way. Second reason is that having that kind of module would be a good example for 3party modules how to implement other spam protection (using hooks). It is similar to ZAuthModule which is an example of how to use Authentication/Authorisation Api.

**Comment by Guite** [comment]
:-1: for another core module

I can imagine a module which is included during CI build, like Profile and Legal. But I see no requirement for a system module here.

**Comment by Guite** [comment]
One reason is that there are many sites who do not need any spam protection functionality (primarily because registration is disabled). Imho system modules should only provide stuff which is used by all sites.

**Comment by craigh** [comment]
> 👎 for another core module

agreed 100%

of course anyone is welcome to create a module to do anything you like. I'm sure it would be well received.

The core will not be focusing on this.
