### ISSUE TITLE
Create UserAdministrationApi

### ISSUE THREAD

**Issue by craigh** [zikula/core#3265]
Create a public service in the UsersModule that provides methods to validate and create a new user, delete a user, ...?

refactor Users and ZAuth to use the methods

the create/validate should take an associative array as a single argument.

**Comment by robbrandt** [comment]
So I need just such a thing. I have a custom authentication where a user account is created if and only if the login authenticates against an external site.  So user account creation happens immediately after authentication if the user account does not already exist.

My current code is derived from the ZAuth Authenticate by field function, with modifications:

`    protected function authenticateByField(array $data, $field = 'uname')
    {
        if (isset($data[$field])) {
            $mapping = $this->getMapping($field, $data[$field]);
            $loggedinuser = $this->passwordApi->passwordsMatch($data['pass'], $data[$field]);
            if ($loggedinuser) {

                if (!$mapping) {
                    $userEntity = new UserEntity();
                    $userEntity->setUname($loggedinuser->user->name);
                    $userEntity->setEmail($loggedinuser->user->mail);
                    $userEntity->setAttribute(UsersConstant::AUTHENTICATION_METHOD_ATTRIBUTE_KEY, "drupal_uname");

                    $registrationHelper = new RegistrationHelper();
                    $registrationHelper->registerNewUser($userEntity);
                    $data = array();
                    $data['uname'] = $loggedinuser->user->name;
                    $data['email'] = $loggedinuser->user->mail;
                    $this->register($data);
                } else {
                    //$this->session->getFlashBag()->add('error', $this->translator->__('Login failed.'));
                }
                return $mapping->getUid();
            } else {
                $this->session->getFlashBag()->add('error', $this->translator->__('Login failed.'));
            }

        }

        return null;
    }`

It crashes at $registrationHelper = new RegistrationHelper(); with

Catchable Fatal Error: Argument 1 passed to Zikula\UsersModule\Helper\RegistrationHelper::__construct() must implement interface Zikula\ExtensionsModule\Api\ApiInterface\VariableApiInterface, none given, called in {...}/modules/zikula/DrupalAuthModule/AuthenticationMethod/AbstractNativeAuthenticationMethod.php on line 125 and defined

I have these namespaces included:

use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\ExtensionsModule\Api\ApiInterface\VariableApiInterface;
use Zikula\UsersModule\AuthenticationMethodInterface\NonReEntrantAuthenticationMethodInterface;
use Zikula\DrupalAuthModule\Api\ApiInterface\PasswordApiInterface;
use Zikula\DrupalAuthModule\Entity\AuthenticationMappingEntity;
use Zikula\DrupalAuthModule\Entity\RepositoryInterface\AuthenticationMappingRepositoryInterface;
use Zikula\DrupalAuthModule\DrupalAuthConstant;
use Zikula\UsersModule\Entity\UserEntity;
use Zikula\UsersModule\Constant as UsersConstant;
use Zikula\UsersModule\Helper\RegistrationHelper;

Looking for ideas...

**Comment by Guite** [comment]
Instead of `$registrationHelper = new RegistrationHelper();` do `$registrationHelper = $this->get('zikula_users_module.helper.registration_helper');`

**Comment by robbrandt** [comment]
at
$registrationHelper = $this->get('zikula_users_module.helper.registration_helper');

I get 

Attempted to call an undefined method named "get" of class "Zikula\DrupalAuthModule\AuthenticationMethod\NativeUnameAuthenticationMethod".
Did you mean to call e.g. "getAlias", "getDescription", "getDisplayName", "getLoginFormClassName", "getLoginTemplateName", "getRegistrationFormClassName" or "getRegistrationTemplateName"?

**Comment by craigh** [comment]
inject the registration helper into the `Zikula\DrupalAuthModule\AuthenticationMethod\NativeUnameAuthenticationMethod` class

**Comment by robbrandt** [comment]
Yeah I think I'm going to need a little bit more help than that.  I'm still on the steep part of the learning curve here. Thanks though.

**Comment by craigh** [comment]
time to learn about dependency injection 😄 

for Core 3
https://symfony.com/doc/current/components/dependency_injection.html

for Core 2
https://symfony.com/doc/3.4/components/dependency_injection.html

**Comment by robbrandt** [comment]
Thanks, I did find something similar before I posted, but I couldn't get it to work after about an hour of experimentation.  Your link (for Core 2) is more specific so hopefully I will be more productive with it.

**Comment by robbrandt** [comment]
Well it seems straightforward enough, once I determined that Zikula uses the yml approach to dependency injection.  Still not working though. Not sure if I am missing Symfony knowledge or Zikula knowledge. Probably both.

Seems to me that I should be handling the injection at 
modules/zikula/DrupalAuthModule/Resources/config/authentication.yml
I have modified zikula_drupalauth_module.authentication_method.drupal_uname as
services:
    zikula_drupalauth_module.authentication_method.drupal_uname:
        class: Zikula\DrupalAuthModule\AuthenticationMethod\NativeUnameAuthenticationMethod
        arguments:
            - "@zikula_drupalauth_module.authentication_mapping_repository"
            - "@session"
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
            - "@validator"
            - "@zikula_drupalauth_module.api.password"
            - "@zikula_users_module.helper.registration_helper"
        tags:
            - { name: zikula.authentication_method, alias: "%zikula_drupalauth_module.authentication_method.alias.drupal_uname.value%" }

It also seems to me that authentication.yml is read at installation, so I have uninstalled the module and reinstalled it.  But I am getting the same error message as before.  When I run the authentication through the debugger, I can see that the helper object is not contained within the authentication method.

What am I missing?

**Comment by craigh** [comment]
you probably need to rebuild the container. this can be done easily by changing 

https://github.com/zikula/core/blob/master/src/app/config/parameters.yml

change `env` from `prod` to `dev`

this forces the container to rebuild always. It is slower but an easier development environment.

**Comment by craigh** [comment]
also - this should probably all be removed from this ticket @Guite since this is all just support talk. In the future @robbrandt this should probably happen in slack.

**Comment by robbrandt** [comment]
> you probably need to rebuild the container. this can be done easily by changing
> 
> https://github.com/zikula/core/blob/master/src/app/config/parameters.yml
> 
> change `env` from `prod` to `dev`
> 
> this forces the container to rebuild always. It is slower but an easier development environment.

Identical results.  The helper object is still not contained within the authentication method.  I tried changing env to dev in both parameters.yml and custom_parameters.yml.  The debugger toolbar does launch, so I am pretty sure that's working ;)

**Comment by robbrandt** [comment]
> also - this should probably all be removed from this ticket @Guite since this is all just support talk. In the future @robbrandt this should probably happen in slack.

Yes, I started there but @Guite pointed me to this thread.  He probably thought there was already more here than milestone entries, or didn't think I'd need as much help as I do.

We can delete the comments (I guess) when we are through.

**Comment by robbrandt** [comment]
So I had need of such an API for a 3rd party auth module I am writing.  Since none exists yet, @Guite suggested I document my results here.

My need, in a nutshell, is to authenticate against an external CMS that manages a CRM database as well.  This database contains "society membership" (not web site membership) data.  The external authentication can only apply to visitors who already have membership in the society, so no account creation user interface in Zikula is required; they simply log in, and if an account in Users is not already there, one needs to be created.  After that, a REST query is performed against to CRM to determine that their society membership is current, and their membership in a Zikula permission group is maintained accordingly. FWIW, my module is basically a clone of the ZAuth module, with modifications to the Authentication methods.

To implement this without an API, I needed to use dependency injection.  It was straightforward enough, but a learning curve had to be dealt with. The dependencies that needed to be handled were for RegistrationHelper, UserRepositoryInterface, and GroupRepositoryInterface.

I needed to learn how Zikula handled dependency injection, namely that it uses the YAML approach with the configuration files at Resources/config/.yml and figure out that proper arguments for each dependency.

I had to add "use" namespaces for the classes needed, and figure out the full paths to the namespaces.

I had to add appropriate parameters to the construct, and assign the values to object attributes.

Lastly, for each of the entities I needed to manipulate, I needed to learn their methods, parameters and syntax.  This meant:
$this->registrationHelper->registerNewUser($userEntity);
(for new users who hadn't logged in before)

$userEntity = $this->userRepository->find($uid);
(for existing users, needed for Group management)

$groupEntity = $this->groupRepository->find($gid); 
(to load the Zikula group to manage)

$isgroupmember = $userEntity->getGroups()->contains($groupEntity);
(to determine if visitor is already a member of the group)

$userEntity->addGroup($groupEntity);
(to add the vistor)

$userEntity->removeGroup($groupEntity);
(to remove the visitor)

Also, I should mention that an auth record needed to be created as well, but since that was already in scope of the function I was modifying, there were no dependency issues and it was pretty easy.

This isn't a huge amount of work if you are already versed in Zikula/Symfony.  Quite a bit more, if you are not.

What would be helpful for a UserAdministrationAPI (and Groups API) would be something that handled all the dependency injection, and allows you to pass in the needed parameters in text values rather than have to build objects just to get the parameters passed, as in 

$userEntity = $this->userRepository->find($uid);
$groupEntity = $this->groupRepository->find($guid);
$isgroupmember = $userEntity->getGroups()->contains($groupEntity);

just to find out if (for example) user 12 is a member of group 3.

Something like a "Create User" API is somewhat more complicated with the newer approach of having the authentication data in a different entity; you wouldn't want to create a user without an appropriate authentication, so maybe the Create User API would include parameters for which authentication method to use, and the appropriate values for that as well.

**Comment by Guite** [comment]
sidenote: if the API would already be there you would also use dependency injection to retrieve it instead of the other stuff; but starting with core 3 you won't need any YAML to do this, but just add the arguments to your class constructor and/or other methods; the rest is then done automatically by Symfony's autowiring functionality ;-)

**Comment by robbrandt** [comment]
That sounds ideal. Does the autowiring also apply to 3rd party modules, or just core modules?

**Comment by Guite** [comment]
3rd party modules may also use it and it is recommended for core-3 modules, but not mandatory

**Comment by craigh** [comment]
👍

**Comment by Kaik** [comment]
I think it relates to #2931 I know it is about permissions but that "requires" Users to be "symfony users"
I think there is a lot to gain aligning our users with sf users or even it is inevitable -  but not like Thanos ;)

**Comment by Guite** [comment]
> I think it relates to #2931

at most a little bit, if at all

This is about introducing an API for easier and consistent management.
The other one should be looked at independently.

> I think there is a lot to gain aligning our users with sf users or even it is inevitable

Which does not mean that it needs to be done as part of *this* ticket.

**Comment by craigh** [comment]
> I think it relates to #2931

not even remotely.
