### ISSUE TITLE
extract translation of theme gives unexpected files

### ISSUE THREAD

**Issue by rallek** [zikula/core#3367]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.5
| PHP Version       | 5.5.30

### Expected behavior
extract translation via ``php app/console translation:extract en --bundle=ZikulaBoostrapTheme --enable-extractor=jms_i18n_routing --output-format=pot`` would create something similar than ``zikulabootstraptheme.en.pot`` 

### Actual behavior
``zikula.en.pot`` and ``routes.en.pot`` are created, nothing else.

### Question?
Is this correct?

**Comment by craigh** [comment]
this is the expected behavior because BootstrapTheme is a Core theme:

https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/Bundle/AbstractCoreTheme.php#L20

Core Themes (and modules) all use `zikula` as the translation domain:

https://github.com/zikula/core/blob/1.4/src/themes/BootstrapTheme/ZikulaBootstrapTheme.php#L16
