### ISSUE TITLE
Overriding login/register templates not possible in theme.

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3401]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.5
| PHP Version       | 5.x

### Problem:
Cannot override login/register template inside a theme.

### Reson

Because event handler responsible for overriding the template that is called using namespace is not taking account of ZikulaUserModule and ZikulaZAuthModule work in collaboration while displaying mentioned pages.

Using template call other that FQN works.

**Comment by craigh** [comment]
I'm sorry, but I cannot understand this ticket. You need to use sentences and punctuation and organize your thoughts. Please rephrase the original ticket and explain more specifically.

**Comment by Kaik** [comment]
Please take a look now.

**Comment by craigh** [comment]
rephrasing:

using `ZikulaZAuthModule:Authentication:UnameLogin.html.twig` instead of 'namespaced' template naming (e.g. `@ZikulaZAuthModule/Authentication/UnameLogin.html.twig`) in an AuthenticationMethod class ([example](https://github.com/zikula/core/blob/ce9260a54d368a13351dc9a915f36313ef2df7c7/src/system/ZAuthModule/AuthenticationMethod/NativeUnameAuthenticationMethod.php#L53-L64)) will solve this problem.

**Comment by craigh** [comment]
@Kaik please submit a PR with the fix you recommended.
