### ISSUE TITLE
some strings are missing in translation files

### ISSUE THREAD

**Issue by rallek** [zikula/core#3433]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6 ci.build 98
| PHP Version       | 5.5.30

### Expected behavior
all English strings should be available for translations.

### Actual behavior
small issue!

In plugin list of the extensions the table head is not available in current translation templates. See image:
![grafik](https://cloud.githubusercontent.com/assets/935250/22524503/cd30e398-e8c3-11e6-9037-96a9c8fb7bd7.png)

Or did I just do not find it?

**Comment by craigh** [comment]
do you mean this?

![cd30e398-e8c3-11e6-9037-96a9c8fb7bd7](https://cloud.githubusercontent.com/assets/350048/22525504/6aa3d5ce-e895-11e6-9177-d305cb58d579.png)

**Comment by rallek** [comment]
I was looking for e.g. ``Internal Plugin name``

**Comment by craigh** [comment]
The entire template is an old Smarty template and will not be updated. The keys _might_ be in the old POT file that is still generated and available. I think you can still translate it and use like you used to - but not certain. In any case, this is a won't fix because the plugin idea is deprecated and will not be updated. Sorry!

**Comment by rallek** [comment]
I just checked. ``Plugins list`` is available but not used. So I translated it already to ``Pluginliste`` but as you can see there is ``Plugins list`` given.

``Extensions`` I did not translate as I think it is better to use the English word.

**Comment by rallek** [comment]
It is fine for me. No problem. I just want not to miss to report the information.
