### ISSUE TITLE
ReferenceError: Can't find variable: Translator

### ISSUE THREAD

**Issue by shefik** [zikula/core#3546]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.6
| PHP Version       | 5.6

### Expected behavior

JavaScript console should not throw an error.

### Actual behavior

Error in JavaScript console

```ReferenceError: Can't find variable: Translator```

File loaded is `/translations/zikula_javascript`

### Steps to reproduce

Load homepage of your site.

**Comment by craigh** [comment]
please test with 1.4.6 and report. thank you

**Comment by shefik** [comment]
I am already using 1.4.6. I typed the incorrect version number.

**Comment by craigh** [comment]
possible for you to test with 1.5?

http://ci.zikula.org/job/Zikula_Core-1.5.0/lastSuccessfulBuild/

I sort of remember fixing something like this already.

**Comment by craigh** [comment]
I thought that I could reproduce the bug but my version of the bug was caused by a different bug that I introduced yesterday (fixed [here](https://github.com/zikula/core/commit/dea91d9e8a3408ad00b99944b3c64a6f04cceab3)) so I don't think that is the cause of your problem.

now I can no longer reproduce your bug with 1.5.0.

will you please test with 1.5.0 and see if the problem persists.

**Comment by craigh** [comment]
fyi - the error causing my issues locally were malformed data in the combined JS file - this was caused by me accidentally including a CSS file into it. This was corrected above, but my guess is that you've got other malformed data in your combined JS file (possibly included by non-core files) causing the same error. You can disable asset combination and debug the problem. I'll guess you have other errors in your console than the one you have reported but you thought them unrelated, but one is causing the other.

**Comment by craigh** [comment]
no response. closing
