### ISSUE TITLE
Have we over-engineered translation?

### ISSUE THREAD

**Issue by craigh** [zikula/core#3551]
@Kaik - you did most of the work implementing translation in Zikula.

This (http://symfony.com/doc/2.8/translation.html#configuration) indicates that in order to configure translation, a small step is required. But it seems we have much more in our implementation. Have we over-engineered this? Or is there a reason all that is required? Maybe if you could help me understand.

**Comment by Kaik** [comment]
Hmm... hard to say now... need to check exactly. What I remember we have recreated Zikula translations using Symfony's translator this includes translation methods ie `` __() `` and translation folders

**Comment by craigh** [comment]
we want to keep `$translator->__()`but not sure what you mean by folders. We will use `Resources/translations`

**Comment by Kaik** [comment]
Hmm... take a look here I have marked this for improvements. https://github.com/zikula/core/blob/1.5/src/lib/Zikula/Common/Translator/Translator.php#L128
I think there was another folder called 'locale' as well and two ways of naming files zikula and symfony I will investigate it this week.

**Comment by craigh** [comment]
yes - in Core-1.5 the old system (only) still users `/locale` dir, but the new system only will use `Resources/translations` (standard symfony)

**Comment by Kaik** [comment]
I do not really have time now to dive into it again, but what I remember is that I have used some code that is mostly a copy of jms translator(I think..) and I was considering that default Symfony translator should be able to handle this, but BC so I had to extend Symfony's translator with our Zikula translator and use it instead. All of this was needed because I wanted to be able to load our translation files - Symfony supports automatic loading but these are loaded by names and our names were different and including `` locale `` folder some domain locale information's were stored as folder name instead of file name as it is in Symfony `` translations `` 

If we drop `` locale `` support (if is not dropped already) then there is still need to be able to load the file with a specific file name and then our extension ``.po``

**Comment by Guite** [comment]
@craigh can this be closed? Or do you suspect specific code to be unneeded?

**Comment by Guite** [comment]
Closing in favour of #3941 which suggests dropping our custom stuff and just proceed with Symfony's translator.
