### ISSUE TITLE
Examine Categories BC break

### ISSUE THREAD

**Issue by Guite** [zikula/core#3661]
See https://github.com/Guite/MostGenerator/issues/1077

**Comment by craigh** [comment]
is the only problem `setCategory_Id`? because if so, I'm not sure that is fixable. The entity now requires a _related entity_ (the category) not simply the id, so setting the id doesn't work. If this is the only break, then I propose we simply document it and leave it

**Comment by craigh** [comment]
I think (when I was refactoring) I was assuming that mod dev would not be calling `Zikula\CategoriesModule\Entity\CategoryRegistryEntity::setCategory_id()` directly. Can I see the code that calls this?

refs https://github.com/zikula/core/pull/3494/files#diff-b699a1c19a6f474123820abfd9b94827

**Comment by Guite** [comment]
This is used in the installer for creating category registries for a module. See here: https://github.com/Guite/MostGenerator/blob/master/bundles/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/cartridges/zclassic/controller/Installer.xtend#L124

See also:
https://github.com/zikula-modules/Pages/blob/master/PagesModuleInstaller.php#L230

**Comment by craigh** [comment]
Pages is using the new methods (core-2.0) there, but probably shouldn't be...

In core 1.3 (and 1.4, < 1.4.6?), the "proper" way to do it would be to use `\CategoryRegistryUtil::insertEntry`

see https://github.com/craigh/PostCalendar/blob/master/lib/PostCalendar/Installer.php#L296

since then, the proper way is to use the new API

`\Zikula\CategoriesModule\Api\CategoryRegistryApi::insertRegistry`

I'm not sure that it is reasonable for a developer to expect that _every line of code_ in a release will never change. Only public facing APIs can be expected to maintain full BC. Otherwise BC is impossible, right? Directly manipulating core entities _shouldn't_ be encouraged I think.

This probably opens a larger conversation about what can and cannot be considered "API" and what we can promise to maintain full BC for as we move forward with Core-2.0.

In _this_ case, while we could create an empty method `Zikula\CategoriesModule\Entity\CategoryRegistryEntity::setCategory_id()` that does nothing, we cannot create a functional one, because setting the ID is no longer possible.

**Comment by Guite** [comment]
I agree.
Closing this one (already added a fix to the generator).

**Comment by craigh** [comment]
Perhaps the generator should be using \Zikula\CategoriesModule\Api\CategoryRegistryApi::insertRegistry() 😉

**Comment by Guite** [comment]
But CategoryRegistryApi is deprecated...

**Comment by craigh** [comment]
Lol. Oops
