### ISSUE TITLE
[Releng] Add docker support

### ISSUE THREAD

**Issue by craigh** [zikula/core#3688]
https://docs.docker.com/engine/userguide/

Add a dockerfile and whatever else is required to support zikula on docker

**Comment by Kaik** [comment]
:+1:

**Comment by Kaik** [comment]
I have been playing with docker and symfony 4 (api so no front-end) and it is not that easy.
I mean it is straight forward to make it working, but to make it working properly so it fits our needs it's not that easy.

Main question is how far we want to go with docker, because you can go all the way down. Starting from a dev image and test image just for devs ending with prod image, volumes, micro services and zikula network - really nice stuff. I'm not an expert but it is very handy to have thing up and running just with one or two commands...


Next year hopefully I will have more free time for Zikula and I will be able to do some work.

**Comment by Guite** [comment]
https://github.com/eko/docker-symfony
https://dev.to/martinpham/symfony-5-development-with-docker-4hj8

**Comment by Guite** [comment]
I think we could reuse this docker-symfony thing as a foundation; the question is whether we need to provide it at all though; there is also [this vagrant stuff](https://github.com/zikula/core/blob/master/vagrant-bootstrap.sh) Christian added a good while ago (see also [this](https://github.com/zikula/core/blob/master/INSTALL-2.0.md#vagrant-installation)); no idea if this still works; probably all these things are not really part of the core project, but could be separated into other dedicated repositories like zikula/container-docker, zikula/container-vagrant, etc.; just my 2 cents ...

**Comment by Guite** [comment]
https://github.com/dunglas/symfony-docker

**Comment by craigh** [comment]
created https://github.com/zikula/core-dev-docker
