### ISSUE TITLE
Module docs

### ISSUE THREAD

**Issue by Kaik** [zikula/core#3739]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.x.x
| PHP Version       | 5.x

Hi, I just realized that someone I think @Guite have done nice help function for admin panel module.
I remember thinking about that long time ago and this help function could do a lot of good things like load files from docs directory there is another similar help function in extensions module. 

It's feature to discuss we could have nice docs for users, admins and developers (dev mode) but this requires that we/developers would need to add to ``Resources/docs`` folders like ``user admin dev `` in each module and place there some doc files (or something like that) so help function could read those and display. Other options like different languages etc.. are also possible. This is a general idea to discuss.

**Comment by Guite** [comment]
cc @rallek

**Comment by Guite** [comment]
For reference: there is already something prepared in the Extensions module.
See `ExtensionsInterfaceController#helpAction`.

**Comment by Guite** [comment]
Thoughts from #2503:

Last week I talked with @rallek about **user docs** and we agreed that it would be advantageous to have these directly inside the application instead of separate documents.

How about this (again, for user docs):

Step 1:
- establish a structure for module-based documentation in Markdown format (this should consider the possibility to add translations)
- automatically provide a *help* or *manual* link in the admin menu of a module (similar to the *hooks* link) if Markdown files are available (could be exposed using a capability to avoid file system scans); use markdown parser to display the docs in html
- default way to *show* this documentation, for example using a modal window or a sidebar (like mmenu, but on the right side)

Step 2:
- maybe implement an additional functionality to create a *complete manual* by combining the markdown files of all available modules into one document (whereby each extension and theme are included as a sub chapter)
- possibility to create pdf files for single extensions or the complete manual

Benefits:
- documentation is maintained directly with the component instead of elsewhere
- context sensitive: users find documentation right at the page where they need it
- easy to handle for different versions (documentation is updated together with the code)
- easy to avoid that docs become outdated
- easy way to contribute as Markdown is simple
- easy to translate
- possibility to create a central documentation automatically (using CI) to publish it on zikula.org for example

Aspects to think about:
- updating translations: maybe we can/should use gettext or something else so that updates can be reflected into existing translations without having to review everything again and again
- deep links between the docs of different extensions (e.g. link a doc section of *AdminModule* inside the docs of *FormiculaModule*)

**Comment by Guite** [comment]
Possible inspiration: Docs for the core are automatically deployed to https://docs.ziku.la/

**Comment by Guite** [comment]
Intermediate results after discussions with @rallek, @craigh and @gfr.
Note I removed all "advanced" and "comprehensive" features which could still be added at a later stage. Let's do it step by step and do less first, but properly.

Goals:
- Make usage so easy that docs are not needed much. We can simply add most important stuff directly to admin templates. A help system should only be provided in addition but should not be required.
- Keep it simple stupid / avoid complexity
- Make it simple for module devs to motivate them to really write something (i.e. not much effort to write some Markdown which will be shown by Zikula automatically)

Proposal:
- An extension may provide Markdown files in `.../Resources/docs/help/<language-code>`, for example `Resources/docs/help/de/` with a fall back to `Resources/docs/help/en/`.
- There is already a controller action prepared in the Extensions module in `ExtensionsInterfaceController#helpAction`. This can be used for showing a help page.
  - It receives an extension name (like `AcmeFooModule`) and checks if docs are available.
  - Optionally it can receive a file name (`foo` with fall back to `README`), so it looks for `...Resources/docs/help/<language>/<file>.md`.
  - Ability to show Markdown as HTML is already there ([markdown_to_html filter](https://twig.symfony.com/doc/3.x/filters/markdown_to_html.html))
- automatically provide a *help* link in the admin menu of an extension (similar to the *hooks* link) if docs are available
  - either open in separate page
  - or show in sidebar at the right
  - or open a modal

Benefits:
- documentation is maintained directly with the component instead of elsewhere
- context sensitive: users find documentation right at the page where they need it
- easy to handle for different versions (documentation is updated together with the code)
- easy to avoid that docs become outdated
- easy way to contribute as Markdown is simple
- easy to translate
