### ISSUE TITLE
Upgrade 1.3.13 -> 1.5.1 authentication method error

### ISSUE THREAD

**Issue by nmpetkov** [zikula/core#3798]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.5.1 build 36
| PHP Version       | 5.6

### Expected behavior
No error in upgrade.

### Actual behavior
At the very beginning of the upgrade, after first screen, pressing button "Administrator log-in", error:
Invalid authentication method.
500 Internal Server Error - LogicException
![image](https://user-images.githubusercontent.com/628801/29961059-cbe65344-8f06-11e7-9365-fb2b993405ba.png)

ADDITIONAL INFORMATION:
After searching the reason, I found authentication method is empty (not passed to users module).

### Steps to reproduce
Trying to upgrade a 1.3.13 site according to instructions here:
https://github.com/zikula/core/blob/1.5/UPGRADE-Core1.x.md

**Comment by Kaik** [comment]
I can confirm this error on 1.3.10 to 1.5.0 upgrade.

**Comment by Kaik** [comment]
I was able to trace it to siteOffListener, I have not traced that further just disabled this listener and upgrade screen showed up... then after login, there was a problem with a theme in user util but I was able to pass this as well and upgrade succeeded. 1.3.12 -> 1.5.0 

Looks like site off listener is showing url that redirects to normal login, while it should show plain html login form and log in using UsersModule AccessController upgradeAdminLoginAction.

**Comment by craigh** [comment]
@nmpetkov can you provide me with the DB and the login credentials you are trying to use?

**Comment by nmpetkov** [comment]
DB credentials are entered in respective files, as per upgrade instructions. The problem is not in DB credentials.
In fact I do not used any login credentials. The problem accrues before any login screen to appear.
Here is screen which says that will go to login screen, but error appear immediately after pressing the button "Administrator log-in".

![image](https://user-images.githubusercontent.com/628801/30004751-b7df3be4-90dd-11e7-8ee1-9ada8aa9ec44.png)

**Comment by nmpetkov** [comment]
Additional info: in the 1.3.13 site, which is currently working well and is in production state, I use normal username/password method to enter.
Database I copied to test upgrade procedure.

**Comment by craigh** [comment]
if you want me to try to fix this, I will require your DB and login credentials.

**Comment by craigh** [comment]
meaning - please email to me. I will not share them with anyone (note I said _login_ credentials - not _DB_ credentials).

**Comment by KratorD** [comment]
I have the same error (ZK 1.3.10 to ZK 1.5.0).
The site is currently offline... Press the button and then...error.

**Comment by KratorD** [comment]
@craigh Do you need a DB and credentials yet? I can provide this if you wish it in order to resolve this bug.
Thanks.

**Comment by KratorD** [comment]
I can confirm that this error is present in the upgrade from 1.3.10 to 1.4.6 too. When you access to /upgrade, the web show "site is offline". You try login, but you retrieve an error 404 (Object not found) for the URL yoursite/users/upgrade-login?authenticationMethod=native_uname
So, I think that the problem is before to ZK 1.5 or ZK 2.0.
@craigh @Guite do you need more information about this? I think that this must to be fixed in order to upgrade this sites with ZK 1.3.x to new Zikula.

Thanks for all.

**Comment by Kaik** [comment]
H, just quick one the problem is that site off listener is getting involved when it should not.... and it thinks that system is in installed state and there is a normal way to login, and it "thinks" that only thing is involved is that the site is off... this is not the case when the system is upgrading...  there used to be a solution/howItWorksBefore for this situation but somewhere it was disabled and redirected to "advanced" normal login...

if you are doing upgrade locally it is ok to completely disable site off listener... upgrade works and there is no security problem, but if you want to do upgrade online and you consider security you need to wait for the fix.

**Comment by craigh** [comment]
I am able to reproduce this bug with the [1.3.10 test db](https://github.com/zikula/core/blob/1.5/test_dbs/core1310.sql) and upgrade to current 1.5.5-dev

**Comment by craigh** [comment]
1) the SiteOffListener is _correctly_ redirecting to login. the problem is that there are no _active_ authentication methods in the DB before the upgrade completes. So `$selectedMethod` is null [here](https://github.com/zikula/core/blob/b5dc447c8de675fedde5daecb0589b6334cdc839/src/system/UsersModule/Controller/AccessController.php#L59)

This can be corrected by adding something like

            $currentInstalledVersion = $this->getParameter('core_installed_version');
            if (version_compare($currentInstalledVersion, '1.4.3', '<')) {
                $selectedMethod = ZAuthConstant::AUTHENTICATION_METHOD_EITHER;
            }

then the problem becomes

2) the lack of correct theme settings preventing the login screen from rendering properly.

@Kaik said
> then after login, there was a problem with a theme in user util but I was able to pass this as well and upgrade succeeded.

so how did you solve this?

**Comment by Kaik** [comment]
@craigh I really do not remember now, it was a long time ago. I'm pretty sure it was some sort of a hack... the only thing I remember now in relation to theme and upgrade is if there is theme_change set to 1 upgrade will look for user theme, not a global one so better set to 0 but looks like your db has (18,'ZConfig','theme_change','s:1:\"0\";')
An error or line would be helpful.

**Comment by craigh** [comment]
I fought with this a little more this morning, but it is very challenging to solve for many reasons.

the BEST workaround is simply to run the upgrade by CLI. this works flawlessly since it requires no login and no themes.

I wonder if the solution might be to simply document this requirement.

**Comment by Kaik** [comment]
I do not know details but why not use hardcoded value for upgrade "ZikulaBootstrapTheme"?

**Comment by craigh** [comment]
I tried that and it didn't work

**Comment by Kaik** [comment]
I'm playing with this now :) well I'm pretty sure I have done it somehow I do not know now, maybe I have used old theme... but now I cannot go thru even with the old theme... Something was changed I think it was 1.5.2 when I will check that now I will see how cli upgrade works because I think there is a problem with it as well...

**Comment by Kaik** [comment]
Ok lool now I know how I did it before... so I just disabled completely wrapping the response in theme here
https://github.com/zikula/core/blob/1.5/src/system/ThemeModule/EventListener/CreateThemedResponseListener.php#L74 so commented out from line 74 to line 86 and 87 changed to ``$event->setResponse($response);`` I was actually wondering at that time how you going to solve it ;) 
```
        // all responses are assumed to be themed. PlainResponse will have already returned.
//        $twigThemedResponse = $this->themeEngine->wrapResponseInTheme($response);
//        if ($twigThemedResponse) {
//            $trimWhitespace = $this->variableApi->get('ZikulaThemeModule', 'trimwhitespace', false);
//            if ($trimWhitespace) {
//                $this->trimWhitespace($twigThemedResponse);
//            }
//            $event->setResponse($twigThemedResponse);
//        } else {
//            // theme is not a twig based theme, revert to smarty
//            $smartyThemedResponse = Zikula_View_Theme::getInstance()->themefooter($response);
//            $event->setResponse($smartyThemedResponse);
//        }
        $event->setResponse($response);

```
Then unstyled login box showed up 
![screencapture-upgrade15-desktop-local-login-1515631377014](https://user-images.githubusercontent.com/966910/34802991-fab2d540-f670-11e7-9293-546285aa7131.png)

when I typed credentials I ended up with this error
```
An exception occurred while executing 'SELECT t0.id AS id_1, t0.method AS method_2, t0.uid AS uid_3, t0.uname AS uname_4, t0.email AS email_5, t0.verifiedEmail AS verifiedEmail_6, t0.pass AS pass_7 FROM zauth_authentication_mapping t0 WHERE t0.uname = ? LIMIT 1' with params ["admin"]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'upgrade15.zauth_authentication_mapping' doesn't exist
500 Internal Server Error - TableNotFoundException
2 linked Exceptions:
PDOException »
PDOException »

[3/3] TableNotFoundException: An exception occurred while executing 'SELECT t0.id AS id_1, t0.method AS method_2, t0.uid AS uid_3, t0.uname AS uname_4, t0.email AS email_5, t0.verifiedEmail AS verifiedEmail_6, t0.pass AS pass_7 FROM zauth_authentication_mapping t0 WHERE t0.uname = ? LIMIT 1' with params ["admin"]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'upgrade15.zauth_authentication_mapping' doesn't exist   -
```
So I have disabled compleatly siteoff listener 
https://github.com/zikula/core/blob/1.5/src/lib/Zikula/Bundle/CoreBundle/EventListener/SiteOffListener.php#L139
```
        return [
//            KernelEvents::REQUEST => [
//                ['onKernelRequestSiteOff', 110] // priority set high to catch request before other subscribers
//            ],
        ];
```
Then upgrade screen showed up then another log in form (this one works!) and then another theme error here
https://github.com/zikula/core/blob/1.5/src/lib/legacy/util/UserUtil.php#L1462
So I just returned theme name :) does not matter which just need to be in the system 
```
 return 'ZikulaAndreas08Theme';
```
And upgrade started nicely and finished then of course when you click Finish button you end up without theme because wrap response in a theme is disabled.
So this works but then I can confirm that #3887 is an issue with web upgrade as well.

Problems.
1.SiteOffListener Login - no zauth module no way to login using your solution it just goes to theme error before zauth error kicks in
2. Theme - at this stage there is no bundles table no way to get new theme - I do not know how it would behave with an old theme - because I have changed Default Theme to ZikulaBootstrapTheme in db. Maybe theme error would not show if I would leave old theme in db and in the system...
3 At this stage after second login Theme bundles table is present but legacy core cannot boot

Solutions hmm as you can see I'm good at commenting out stuff until it works :) 
I think that if you could fix site off listener to use https://github.com/zikula/core/blob/1.5/src/lib/Zikula/Bundle/CoreInstallerBundle/Validator/Constraints/AuthenticateAdminLoginValidator.php#L65 then login problem would be gone.
With theme, we could make wrap response in theme listener react when system is in upgrade stage to return plain response (no theme is needed at this stage) and then fix last theme error same way as well (hardcode to ZikulaBootstrapTheme in case of upgrade stage)

Another solution is to display info to use cli upgrade and forget about web upgrade between 1.3.x and 1.5
Btw please take a look at #3887 
@craigh

**Comment by Guite** [comment]
Sorry, this has become a won't fix because we aren't able to support upgrading from 1.3 to 3.0.0 (and there won't be future bugfix updates for 1.5 and/or 2.0)
