### ISSUE TITLE
Nginz server config for Zikula

### ISSUE THREAD

**Issue by nobicycle** [zikula/core#3820]
Hi, I am having difficulty getting Zikula working under nginx.

| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.1
| PHP Version       | 7.1.9

### Expected behavior
Web install would open in browser

### Actual behavior
HTTP ERROR 500
2017/09/29 11:39:08 [error] 17601#17601: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/srv/http/zikula/app/../vendor/autoload.php): failed to open stream: No such file or directory in /srv/http/zikula/app/autoload.php on line 19
PHP message: PHP Fatal error:  require(): Failed opening required '/srv/http/zikula/app/../vendor/autoload.php' (include_path='.:') in /srv/http/zikula/app/autoload.php on line 19" while reading response header from upstream, client: 127.0.0.1, server: zikula.localdomain, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "zikula.localdomain

### Steps to reproduce
nginx server config here:

[zikula.txt](https://github.com/zikula/core/files/1343057/zikula.txt)

**Comment by craigh** [comment]
hello @nobicycle and welcome to zikula. I'm sorry you're having trouble. I've never personally used nginx so I can't help directly.

zikula uses symfony, so you probably should configure nginx exactly the same as symfony with one modification:

so start with this: https://www.nginx.com/resources/wiki/start/topics/recipes/symfony/

then you can probably remove the entire section that starts with `location ~ ^/(app_dev|config)\.php(/|$)` because we do not use those files at all.

then you will need to configure `index.php` to be the main front controller instead of `app.php`. I don't know how to do this but I suspect that if you change the next section from

`location ~ ^/app\.php(/|$)`

to

`location ~ ^/index\.php(/|$)`

then it may work. but like I said, I don't know. I've never used it.

If you come up with a working solution, I would love to include it with zikula. So please do keep us informed.

**Comment by nobicycle** [comment]
I tried but failed. Thanks for the suggestion
