### ISSUE TITLE
Not possible to search pending registrations

### ISSUE THREAD

**Issue by paustian** [zikula/core#3928]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.5
| PHP Version       | 5.5.38

### Expected behavior
There should be an option to search through pending registrations to find users who are having problems with the registration process. If you require user validation via Email address, this Email often either gets block by spam or ends up in the junk folder. It then becomes difficult to find them

### Actual behavior
There is no way to search through pending registrations

### Steps to reproduce
Create an account, but don't verify it. Then try to search for in the Users List page

**Comment by Kaik** [comment]
This is a very important thing to have. Someone tried to create an account like 2 years ago and did not finish and now he is asking what to do...

**Comment by Guite** [comment]
@paustian feel free :-)

**Comment by craigh** [comment]
yes this should stay 3.0

**Comment by craigh** [comment]
@paustian, I think https://github.com/zikula/core/commit/bc221d1f72bf572471e08b911e46deae53774eb8 fixed this, right? It added `activated` status (e.g. "active", "pending", etc) to the search fields. Can this be closed?

**Comment by craigh** [comment]
> Then try to search for in the Users List page

Do you mean here:
![Screen Shot 2020-03-22 at 8 10 56 PM](https://user-images.githubusercontent.com/350048/77267520-3e487500-6c79-11ea-9fad-87326051d5e4.png)

Because this now works:
![Screen Shot 2020-03-22 at 8 11 39 PM](https://user-images.githubusercontent.com/350048/77267551-59b38000-6c79-11ea-9438-aff01f5c0d97.png)

I cannot get the 'live search' feature to work at all, so I cannot test that one. (@Guite)

**Comment by Guite** [comment]
> I cannot get the 'live search' feature to work at all, so I cannot test that one. (@Guite)

Live search should only search for active users (see [here](https://github.com/zikula/core/blob/master/src/system/UsersModule/Controller/LiveSearchController.php#L41)) because it is primarily used for assigning users to other data. I would consider adding support for pending registrations there as invalid/unsupported use case.

Probably @paustian was looking for a way in administration like you've shown in your screenshots. Hence, I think this issue is completed. @paustian what do you think?
