### ISSUE TITLE
Make module deactivation/reactivation more robust

### ISSUE THREAD

**Issue by Guite** [zikula/core#3930]
Reactivation of an inactive module may lead to an exception because the kernel does not recognise it yet. It works in a subsequent page load though, so this is not critical.

Example: https://github.com/zikula-modules/Content/issues/302

**Comment by craigh** [comment]
beware. this is a dark hole. symfony bundles are not designed to be dynamically enabled/disabled. We have created a system to compensate for this, but it is flaky. Because the majority of sites enable some modules and then never change this wasn't seen as a problem. The system went through many growing pains to get where it is currently at. Changing it could be problematic.

**Comment by Guite** [comment]
Closing. This does now work like a charm.
