### ISSUE TITLE
Account panel regressions

### ISSUE THREAD

**Issue by Guite** [zikula/core#4072]
1. Visiting `/src/users/account` shows no account links. Not sure whether this is a general problem or only at my site. It seems that the `accountMenus` variable contains six items. But nothing is rendered.
2. The `/src/system/UsersModule/Resources/views/Account/menu.html.twig` template contains commented code which should be removed.
3. If Users module vars (like `accountdisplaygraphics`, `accountitemsperpage`, `accountitemsperrow`) are not used anymore they should be removed from both the code as well as databases (upgrade code)

**Comment by Guite** [comment]
Also the dropdown menus here are missing:

![Screenshot_20200120_090110](https://user-images.githubusercontent.com/277531/72708632-73462780-3b63-11ea-9c94-1fa939c0a88e.png)

**Comment by craigh** [comment]
I was aware of some issues, but it should work. I have this:
![Screen Shot 2020-01-20 at 5 00 11 PM](https://user-images.githubusercontent.com/350048/72760318-5717aa00-3ba6-11ea-99fd-42e96874f231.png)

which I know is wrong, but it is something.

I was actually hoping to ask you for help with this since you know bootstrap better than I do. One problem with the Account menu is that it isn't one unified menu, but several.

**Comment by craigh** [comment]
OLD
![Screen Shot 2020-01-20 at 5 11 16 PM](https://user-images.githubusercontent.com/350048/72764858-b7631780-3bb7-11ea-8ed1-ead6f93f860a.png)

NEW
![Screen Shot 2020-01-20 at 7 04 30 PM](https://user-images.githubusercontent.com/350048/72764863-bd58f880-3bb7-11ea-8c81-215d34844053.png)

**Comment by Guite** [comment]
:+1:  I see it now, too.
