### ISSUE TITLE
Installation fails when using MySQL

### ISSUE THREAD

**Issue by ianfoulds** [zikula/core#4243]
The installation process fails when using a MySQL database, it fails to install the theme module.

| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.13-2.0.15
| PHP Version       | 7.3.3
| MySQL               | 8.0.16

The installation fails showing that the theme module installer failed. An alert popup occurs showing raw HTML code indicating a server 500 error occurred.

After a log of messing about, retrying the installation, checking log files and scratching my head, I eventually set the Symfony config to dev mode and enabled debug before I ran the installation. After hacking the ThemeModuleInstall class I eventually got an error that meant something. You are using a column name of 'system' in the theme table which consequently fails. Hacking the ThemeEntity class to add a name attribute to escape the column allowed the installation  to complete. System was added as a reserved word in MySQL 8.0.3 released on 21/09/2017.

I have tried 2.0.13 through 2.0.15 and all seem to experience he same issue.

I have some questions related to this
1. Do you test your software? Using MySQL as a store would seem be a very common choice to me but this error has been around for quite some time. How come you have not discovered this before? Do you realise how many people have tried to install Zikula and given up!
2. You have some quite frankly poor coding in your installer. How on earth is anyone going to get any sensible errors out of your system when you do stupid stuff like this in your error handler (see below). You just chuck the error away! No wonder there is nothing in any log files to give the poor users an idea of where things are going wrong.

```
    public function install()
    {
        // create the table
        try {
            $this->schemaTool->create([ThemeEntity::class]);
        } catch (\Exception $e) {
            return false;
        }
```

Following on from this painful episode I received yet further SQL errors from a Doctrine join, at which point I gave up.

**Comment by Guite** [comment]
Sorry you encountered such problems.

Some aspects to clarify things:

- We did first tests with MySQL 8 in Sep 2019 and added a fix for the groups table in db162f6f6d2094afa58a53c5c3f0ec2124053866. It may have been released in 2017, but it took another while until it arrived at distributions and systems.
- The problem in the theme module never popped up because the `ThemeEntity` is entirely removed in our 3.0 version which we are working on. Also the problematic installer part is not contained in 3.0 anymore.

We know this situation is far from ideal, but we are working on getting the new version out asap.

The only workaround for 2.0.x is changing the `sql_mode` for backwards compatiblity ([docs](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html)). But there are other problems with PHP 7.3 and 7.4 so we wouldn't recommend using 2.0.x with brand new environments but rather wait for 3.0.

**Comment by Guite** [comment]
Removed the problematic suppression of the exceptions in ce8116a479b925e6f7f974ebe1c005273bf37897

**Comment by craigh** [comment]
So is this a bug report or just a rant? I'm thankful you tried the software and I'm sorry that it didn't work out for you. **There is no need to be rude**.

> Do you test your software?
https://travis-ci.org/github/zikula/core/builds/613392618

Software doesn't work forever with every upgrade of every vendor. While the last release of Zikula 2.0.15 was in Nov 2019, the last real work on it was done in v2.0.10 in Aug 2018. At that time, testing with mysql 8 wasn't done. **Apparently Core-2.0.x isn't Mysql-8 compatible.** The solution to your problem is for you to downgrade to mysql 5. 

I'm impressed that you were capable of tracking down and solving some of the problems. Maybe you should consider trying the master branch and see if that works better for you. We are nearing a beta release and could use your help in tracking down bugs.

**Comment by ianfoulds** [comment]
Apologies if I sounded irate, I've been testing a lot of CMS systems to try and find something sensible, that is also extensible, that an artist friend who is not tech savvy can use. I've tried so many I've lost count. Most of them are only fit for blogs or very basic content when they purport to being something better. I just couldn't believe it would be so hard getting this running when my system appeared to tick all the specified requirements.

I initially wondered if it might be a database issue but I could find nothing in the release documentation that suggested only older versions of MySQL were supported so I assumed I was OK. I'm not going to downgrade, I have too many other things on the go on my dev server.

I'm pretty sure I tried the master branch before I back tracked to V2. I think I ran out of steam when the Pages and WYSIWYG editor modules were not available.

I'll gladly give it another go when it's up to speed for WYSIWYG CMS operation.
