### ISSUE TITLE
[General] remove symfony/symfony dependency

### ISSUE THREAD

**Issue by craigh** [zikula/core#4352]
remove symfony/symfony dependency and replace with only needed components.

this is required as part of https://symfony.com/doc/current/setup/flex.html

at least

but also, just good practice and also current best-practice.

**Comment by Guite** [comment]
isn't this necessarily for 4.0.0 ?
because if we remove something this is a BC break

**Comment by craigh** [comment]
the goal would be to not remove anything 😄 

I believe this simply done.

**Comment by Guite** [comment]
Then the description above is misleading:

> replace with **only needed** components

**Comment by craigh** [comment]
possible you are right. I've done some preliminary research. As far as I can tell, the _core_ is not using

 - component/browser-kit // used in functional tests
 - component/css-selector // used in functional tests
 - component/dom-crawler // used in functional tests
 - component/http-client ?? no? maybe used in functional tests?
 - component/inflector
 - component/ldap
 - component/lock
 - component/process ??
 - component/property-access
 - component/property-info
 - component/serializer
 - component/stopwatch
 - component/templating (maybe used by maker?)
 - component/var-dumper
 - component/var-exporter
 - component/web-link

**Comment by Guite** [comment]
If/After #4514 has been merged the String component's `functions.php` file is included in `bootstrap.php` to make the helper methods available (`u()`, `b()`, `s()`).
This inclusion can be removed again as part of #4352 because then the String component will be explicitly added by composer which adds `"files": [ "Resources/functions.php" ]` to the autoloader ([link](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/String/composer.json#L34)).
