### ISSUE TITLE
[Releng] local release tool

### ISSUE THREAD

**Issue by Guite** [zikula/core#4425]
- [x] Introduce a dedicated repo like *releng-tools*
- [x] Add a console command for replacing versions

**Comment by craigh** [comment]
split is not functioning correctly with regard to tags. at this time, I do not recommend running it at all except in the exact case where a new tag has just been pushed to the core.

**Comment by craigh** [comment]
I would like this to accomplish as much of the release process as possible. Not just increment versions.

A local tool could eventually fully replace CMM .

While the current zsplit tool is written in bash script, I wonder if it is possible to write this as a symfony command or self-contained application. This would mean writing php and using already familiar tools instead of learning bash (for me).

**Comment by craigh** [comment]
looks like we can use symfony/process to run external commands like zsplit 
https://symfony.com/doc/current/components/process.html

https://stackoverflow.com/a/42629988/2600812

possibly using a Single Command Application https://symfony.com/doc/current/components/console/single_command_tool.html

**Comment by Guite** [comment]
There is also the possibility to use a manually triggered GitHub actions workflow: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

**Comment by Guite** [comment]
CMM could then be reduced to fetch releases from GitHub and manage corresponding announcements (News articles).

**Comment by craigh** [comment]
A php library to manage git commands:
https://github.com/czproject/git-php

there are others as well.

**Comment by craigh** [comment]
a start: https://github.com/zikula/rt

**Comment by craigh** [comment]
closing this as initial tasks are complete. of course more features are desired and will be added, but no need to keep this ticket.
